feat(display-assets): display nested assets in model
titel-media/datocms-plugin-media-credits pull request #2
Opened 2021-08-12 15:41 UTC by AaronCGoidel

2021-08-16 14:19 UTC, duksis commented
@dazlious @lmtejada This PR adds functionality for retrieving/listing assets attached to a DatoCMS record.
your feedback and improvement suggestions would be highly appreciated

2021-08-17 07:12 UTC, dazlious requested changes
LGTM overall, some smaller improvements can be made to improve the code quality and readability. Please review the loops with async/await and make sure they really await. Easy way to test that is to run a console log within the loop that iterates and a done log after the loop. If the done is fired before the iteree fire, something is not working correctly.

Some best practices for JS and specifically React:
- always use const and make everything immutable
- use camelCase
- do not repeat yourself

2021-08-17 07:12 UTC, dazlious commented on src/components/Main/Main.jsx
> +  };
Why create array here? 

```suggestion
const parse_field = async ({ field_type: fieldType, api_key: apiKey }) => {
  switch(fieldType) {
    case 'file':
      return plugin.getFieldValue(field.api_key).upload_id;
    case default:
      const itemId = plugin.getFieldValue(apiKey);
      return await parse_nested_content(await client.items.find(itemId))
  }
}
```

2021-08-17 07:12 UTC, dazlious commented on src/components/Main/Main.jsx
> +import { map } from 'lodash-es';
js imports should come before scss

2021-08-17 07:12 UTC, dazlious commented on src/components/Main/Main.jsx
> +  let [source, setSource] = useState('');
always go with const. You will see when you will need a let. But usually 99% of the time it is const in JSX.

2021-08-17 07:12 UTC, dazlious commented on src/components/Main/Main.jsx
> +  };
```suggestion
  const getModel = async (id) => {
    let model = null;
    try {
      model = await client.items.find(id, {});
    } catch (err) {
      if (devMode) {
        console.error(`Could not find model with id ${id}`);
      }
    }
    return model;
  };
```

2021-08-17 07:12 UTC, dazlious commented on src/components/Main/Main.jsx
> +    let ids = [];
const ids. You do not need to reassign ids. Just push onto it

2021-08-17 07:12 UTC, dazlious commented on src/components/Main/Main.jsx
> +      if (typeof obj[property] === 'string' && property !== 'id') {
do `const field = obj[property];`

2021-08-17 07:12 UTC, dazlious commented on src/components/Main/Main.jsx
> +          ids = ids.concat(await parse_nested_content(nested));
push onto ids, so you do not need the let

2021-09-27 14:06 UTC, merged